In [1]:
from algorithms import *
from algorithms.MlpV2 import *
data = Data()
data.print_shapes()
X_train = data.train_data
y_train = data.train_label

(45000, 128)
(45000, 10)
(5000, 128)
(5000, 10)
(10000, 128)
(10000, 10)


In [2]:
X_test = data.test_data
y_test = data.test_label

In [7]:
nn = MlpV2(learning_rate=0.01, batch_size= 64)
nn.set_momentum(0.9)
nn.set_batchNormalizer()
nn.add_layer(128,64,"relu",1)
nn.add_layer(64,32,"relu",1)
nn.add_layer(32,10,"softmax",1)
### Try different learning rate and epochs

#print('loss:%f'%MSE[-1])

In [8]:
X_train.std()

1.1694794554578622

In [12]:
nn.fit(X_train, y_train, epochs= 10)

Epoch: 1  Training Loss: 1.6002385467592466  Time (sec): 2.333219051361084
Epoch: 2  Training Loss: 1.5986918360618818  Time (sec): 1.473358154296875
Epoch: 3  Training Loss: 1.6019005248187506  Time (sec): 2.2081687450408936
Epoch: 4  Training Loss: 1.6033374690395634  Time (sec): 2.0248663425445557
Epoch: 5  Training Loss: 1.6052993927290682  Time (sec): 2.4188342094421387
Epoch: 6  Training Loss: 1.606606587016629  Time (sec): 1.8293616771697998
Epoch: 7  Training Loss: 1.6045658350187926  Time (sec): 1.8360822200775146
Epoch: 8  Training Loss: 1.6079421195084576  Time (sec): 2.290038585662842
Epoch: 9  Training Loss: 1.6091749376071407  Time (sec): 2.0779521465301514
Epoch: 10  Training Loss: 1.606336688879914  Time (sec): 2.0737533569335938


array([1.60023855, 1.59869184, 1.60190052, 1.60333747, 1.60529939,
       1.60660659, 1.60456584, 1.60794212, 1.60917494, 1.60633669])

In [22]:
pred = nn.predict(X_test)

In [23]:
pred.shape

(10000, 10)

In [24]:
p = np.argmax(pred, 1)

In [25]:
print(p[:10])

[6 1 8 8 4 6 1 6 5 1]


In [26]:
sum(p == np.argmax(y_test, 1))

4714

0.37644444444444447

In [ ]:
y_test[:10]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
nn.layers[0].input

array([[ 8.94709363e-01,  4.74420012e-01, -4.15588793e+00, ...,
        -8.99450219e-02,  3.21768991e-01,  2.78092245e-02],
       [ 3.76479437e+00,  1.01376893e+01, -9.33030566e-01, ...,
        -5.58009907e-02,  3.94649540e-01, -8.73867434e-03],
       [ 9.62955809e+00,  4.17867683e+00,  9.12957411e-01, ...,
        -1.15120224e-02, -6.59434717e-02,  7.20981101e-02],
       ...,
       [ 4.66789849e+00,  1.51234512e+00, -5.82175114e+00, ...,
        -1.18824850e+00, -1.33234958e+00,  3.86089254e-01],
       [-6.76424181e+00,  1.30444413e+01, -2.24112088e+00, ...,
         3.04249707e-01, -2.88326186e-01,  3.47208599e-01],
       [-5.21774934e+00,  2.20420563e+00,  2.05170429e-01, ...,
        -1.28454383e-01, -2.60359675e-02,  2.01775540e-01]])

In [ ]:
X_test.std(axis=1)

array([0.87002005, 1.52524759, 1.18347009, ..., 1.61005482, 1.04959738,
       0.81149064])

In [15]:
a = np.array([[1,2,3],[4,5,6]])

In [16]:
b = np.array([[7],[8]])

In [21]:
c = np.concatenate([a,b],axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [25]:
np.random.shuffle(c)

In [26]:
c

array([[4, 5, 6, 8],
       [1, 2, 3, 7]])