In [5]:
from algorithms import *
from algorithms.MlpV2 import *
data = Data()
data.print_shapes()
X_train = data.train_data
y_train = data.train_label

(45000, 128)
(45000, 10)
(5000, 128)
(5000, 10)
(10000, 128)
(10000, 10)


In [6]:
X_test = data.test_data
y_test = data.test_label

In [7]:
nn = MlpV2(learning_rate=0.01, batch_size= 64)
nn.set_momentum(0.9)
nn.set_batchNormalizer()
nn.add_layer(128,64,"relu",1)
nn.add_layer(64,32,"relu",1)
nn.add_layer(32,10,"softmax",1)
### Try different learning rate and epochs

#print('loss:%f'%MSE[-1])

In [8]:
X_train.std()

1.1688609442723896

In [9]:
nn.fit(X_train, y_train, epochs= 10)

Epoch: 1  Training Loss: 2.1713914475733187  Time (sec): 2.705084800720215
Epoch: 2  Training Loss: 1.9168518931184424  Time (sec): 2.357929229736328
Epoch: 3  Training Loss: 1.8339863206112441  Time (sec): 2.4728991985321045
Epoch: 4  Training Loss: 1.7832334100879765  Time (sec): 3.0636868476867676
Epoch: 5  Training Loss: 1.7407575723665656  Time (sec): 2.0835320949554443
Epoch: 6  Training Loss: 1.7073109546532794  Time (sec): 2.21567964553833
Epoch: 7  Training Loss: 1.6777827431506593  Time (sec): 1.7549633979797363
Epoch: 8  Training Loss: 1.653947867620072  Time (sec): 2.7121098041534424
Epoch: 9  Training Loss: 1.628972716775714  Time (sec): 1.5159025192260742
Epoch: 10  Training Loss: 1.6108406275379814  Time (sec): 2.072101593017578


array([2.17139145, 1.91685189, 1.83398632, 1.78323341, 1.74075757,
       1.70731095, 1.67778274, 1.65394787, 1.62897272, 1.61084063])

In [10]:
pred = nn.predict(X_test)

In [11]:
pred.shape

(10000, 10)

In [12]:
p = np.argmax(pred, 1)

In [13]:
print(p[:10])

[5 9 8 8 4 6 3 6 5 1]


In [26]:
sum(p == np.argmax(y_test, 1))

4714

In [ ]:
X_test.std(axis=1)

array([0.87002005, 1.52524759, 1.18347009, ..., 1.61005482, 1.04959738,
       0.81149064])