In [1]:
from algorithms import *
data = Data()
data.print_shapes()
X_train = data.train_data
y_train = data.train_label

(45000, 128)
(45000, 10)
(5000, 128)
(5000, 10)
(10000, 128)
(10000, 10)


In [2]:
X_test = data.test_data
y_test = data.test_label

In [7]:
nn = Mlp(learning_rate=0.001, batch_size= 64)
nn.set_momentum(0.9)
nn.set_batchNormalizer()
nn.add_layer(128,64,"relu",1)
nn.add_layer(64,32,"relu",1)
nn.add_layer(32,10,"softmax",1)
### Try different learning rate and epochs

#print('loss:%f'%MSE[-1])

In [8]:
X_train.std()

1.1683557398897972

In [15]:
nn.fit(X_train, y_train, epochs= 20)

input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 64)
dz (64, 64)
input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 64)
dz (64, 64)
input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 64)
dz (64, 64)
input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 64)
dz (64, 64)
input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 64)
dz (64, 64)
input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 64)
dz (64, 64)
input shape (64, 32)
delta (64, 10)
dz (64, 10)
input shape (64, 64)
delta (64, 32)
dz (64, 32)
input shape (64, 128)
delta (64, 6

array([2.08923446, 2.05183918, 2.02640658, 2.00252384, 1.98166721,
       1.96365848, 1.94710144, 1.93343169, 1.92032292, 1.90548178,
       1.89629698, 1.88594001, 1.87598296, 1.86692233, 1.85823958,
       1.85168973, 1.84044556, 1.83662207, 1.82992485, 1.82201342])

In [10]:
pred = nn.predict(X_train)

In [11]:
pred.shape

(45000, 10)

In [12]:
p = np.argmax(pred, 1)

In [13]:
print(p[:10])

[1 1 6 7 8 0 9 6 2 7]


In [14]:
sum(p == np.argmax(y_train, 1))

11258

In [11]:
16940/45000

0.37644444444444447

In [12]:
y_test[:10]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
nn.layers[0].input

array([[ 8.94709363e-01,  4.74420012e-01, -4.15588793e+00, ...,
        -8.99450219e-02,  3.21768991e-01,  2.78092245e-02],
       [ 3.76479437e+00,  1.01376893e+01, -9.33030566e-01, ...,
        -5.58009907e-02,  3.94649540e-01, -8.73867434e-03],
       [ 9.62955809e+00,  4.17867683e+00,  9.12957411e-01, ...,
        -1.15120224e-02, -6.59434717e-02,  7.20981101e-02],
       ...,
       [ 4.66789849e+00,  1.51234512e+00, -5.82175114e+00, ...,
        -1.18824850e+00, -1.33234958e+00,  3.86089254e-01],
       [-6.76424181e+00,  1.30444413e+01, -2.24112088e+00, ...,
         3.04249707e-01, -2.88326186e-01,  3.47208599e-01],
       [-5.21774934e+00,  2.20420563e+00,  2.05170429e-01, ...,
        -1.28454383e-01, -2.60359675e-02,  2.01775540e-01]])

In [14]:
X_test.std(axis=1)

array([0.87002005, 1.52524759, 1.18347009, ..., 1.61005482, 1.04959738,
       0.81149064])