In [2]:
from algorithms import *
data = Data()
data.print_shapes()
X_train = data.train_data
y_train = data.train_label

(45000, 128)
(45000, 10)
(5000, 128)
(5000, 10)
(10000, 128)
(10000, 10)


In [3]:
X_test = data.test_data
y_test = data.test_label

In [4]:
nn = Mlp(learning_rate=0.001, batch_size= 5000)
nn.set_momentum(0.9)
nn.set_batchNormalizer()
nn.add_layer(128,64,"relu",1)
#nn.add_layer(64,32,"relu",1)
nn.add_layer(64,10,"softmax",1)
### Try different learning rate and epochs

#print('loss:%f'%MSE[-1])

In [5]:
X_train.std()

1.1690781570631141

In [6]:
nn.fit(X_train, y_train, epochs= 5)

Epoch: 1  Training Loss: 2.140103250804842  Time (sec): 2.043877124786377
Epoch: 2  Training Loss: 1.8721844004089807  Time (sec): 1.0551929473876953
Epoch: 3  Training Loss: 1.8543800862784723  Time (sec): 1.0750257968902588
Epoch: 4  Training Loss: 1.8387323544718488  Time (sec): 2.049363136291504
Epoch: 5  Training Loss: 1.843905156210018  Time (sec): 1.31602144241333


array([2.14010325, 1.8721844 , 1.85438009, 1.83873235, 1.84390516])

In [7]:
pred = nn.predict(X_test)

In [8]:
pred.shape

(10000, 10)

In [9]:
p = np.argmax(pred, 1)

In [10]:
print(p[:10])

[3 8 8 8 4 6 3 2 5 1]


In [23]:
nn.layers[0].input

array([[-3.47967057e+00,  9.06426369e-01,  1.25195572e+00, ...,
         8.61874214e-01,  6.31729322e-01,  2.60908392e-01],
       [ 9.94315784e+00, -9.58055259e+00,  5.06857801e+00, ...,
         1.63248427e-01, -3.18574521e-01, -2.67055346e-01],
       [ 4.70429957e+00, -8.83720616e+00,  4.10928532e+00, ...,
         5.57491883e-02,  2.65140024e-01,  1.67865616e-01],
       ...,
       [-1.52911933e+01,  2.50308666e+00, -2.27169405e-01, ...,
        -2.68454413e-01, -6.99688324e-02, -6.08919845e-01],
       [-5.85707877e+00,  2.04437491e+00,  3.65488937e+00, ...,
         7.85415991e-01,  6.86344933e-03,  2.01131653e-02],
       [-1.76542944e+00, -1.89117258e+00, -2.14885246e+00, ...,
        -4.11516440e-01,  1.87276097e-02,  2.38587672e-01]])

In [29]:
X_test.std(axis=1)

array([0.87002005, 1.52524759, 1.18347009, ..., 1.61005482, 1.04959738,
       0.81149064])